### ISSUE TITLE
error when unzip data.zip

### ISSUE THREAD

**Issue by haiahaiah** [JH-lee95/TxtSeg_MTL#5]
Hi, thanks for your work. However, when I unzip data.zip, it throws an error like follows:

> End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data.zip or
        data.zip.zip, and cannot find data.zip.ZIP, period.

**Comment by JH-lee95** [comment]
@haiahaiah I uploaded preprocess.py which pre-process raw wikisection dataset and create the dataset for our model.  please read [here](https://github.com/JH-lee95/TxtSeg_MTL#preparing)
